# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include: all
  recursive: true

build:
  os: "ubuntu-22.04"
  tools:
     python: "mambaforge-latest"
  commands:
    - mkdir build
    - which python
    - cd build && cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX .. && make -j4 all install
    - cd docs && make html
    - mkdir -p $READTHEDOCS_OUTPUT/
    - mv ./docs/build/html $READTHEDOCS_OUTPUT/html
    
conda:
  environment: environment.yml
